[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/api/analyse"
  to = "/.netlify/functions/analyse"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors *"
